name: Utilities
version: '${project.version}'
main: me.accogliente.utilities.Utilities
api-version: 1.19
commands:
  heal:
    usage: /<command>
    description: heal player
  gm:
    usage: /<command>
    description: alt for gamemode
  feed:
    usage: /<command>
    description: feed player
  back:
    usage: /<command>
    description: back to death location
