name: Utilities
version: '${project.version}'
main: me.accogliente.utilities.Utilities
api-version: 1.19
commands:
  heal:
    usage: /<command>
    description: heal player
    aliases:
      - h
  gm:
    usage: /<command>
    description: alt for gamemode
    aliases:
      - g
      - gamemode
  feed:
    usage: /<command>
    description: feed player
    aliases:
      - f
  back:
    usage: /<command>
    description: back to death location
    aliases:
      - b
  utilreload:
    usage: /<command>
    description: reload plugin
    aliases:
      - ur
  spawn:
    usage: /<command>
    description: teleport to spawn
  setspawn:
    usage: /<command>
    description: set spawn location
  wb:
    usage: /<command>
    description: open work banch
    aliases:
      - workbanch
      - craft
  anvil:
    usage: /<command>
    description: open anvil
    aliases:
      - anvil
      - anv
  ec:
    usage: /<command>
    description: open ender chest
    aliases:
      - enderchest
      - echest
