name: Utilities
version: '${project.version}'
main: me.accogliente.utilities.Utilities
api-version: 1.19
commands:
  heal:
    usage: /<command>
    description: heal player
    aliases:
      - h
  gm:
    usage: /<command>
    description: alt for gamemode
    aliases:
      - g
      - gamemode
  feed:
    usage: /<command>
    description: feed player
    aliases:
      - f
  back:
    usage: /<command>
    description: back to death location
    aliases:
      - b
